name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm" # ✅ enables caching for node_modules

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint --if-present

      - name: Build project
        run: npm run build

      - name: Generate ERD diagrams
        run: |
          npx @mermaid-js/mermaid-cli -i docs/erd.mmd -o docs/erd.png
          npx @mermaid-js/mermaid-cli -i docs/erd.mmd -o docs/erd.svg

      - name: Commit ERD diagrams
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(ci): auto-generate ERD diagrams"
          file_pattern: docs/erd.png docs/erd.svg
