name: CI Build + Nightly Maintenance

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *" # every day at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Generate ERD diagrams
        run: |
          npx @mermaid-js/mermaid-cli -i docs/erd.mmd -o docs/erd.png
          npx @mermaid-js/mermaid-cli -i docs/erd.mmd -o docs/erd.svg

      - name: Auto-fix vulnerabilities
        run: npm audit fix --force
