name: Generate ERD diagrams

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-erd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20.19.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Fix security issues automatically
        run: npm audit fix --force || true

      - name: Generate ERD diagrams
        run: |
          npx @mermaid-js/mermaid-cli -i docs/erd.mmd -o docs/erd.png --puppeteerConfig .puppeteer.config.cjs
          npx @mermaid-js/mermaid-cli -i docs/erd.mmd -o docs/erd.svg --puppeteerConfig .puppeteer.config.cjs

      - name: Commit and push ERD diagrams
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/erd.png docs/erd.svg
          git commit -m "chore: auto-generate ERD diagrams [skip ci]" || echo "No changes to commit"
          git push
