name: Generate ERD Diagrams & Security Fixes

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-erd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.19.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run security audit & auto-fix
        run: |
          npm audit fix --force || true

      - name: Install Mermaid CLI
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Generate ERD diagrams
        run: |
          mmdc -p .puppeteer.config.cjs -i docs/erd.mmd -o docs/erd.png
          mmdc -p .puppeteer.config.cjs -i docs/erd.mmd -o docs/erd.svg

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json docs/erd.png docs/erd.svg || true
          git commit -m "chore: auto-fix vulnerabilities & generate ERD [skip ci]" || echo "No changes to commit"
          git push origin main
